### ISSUE TITLE
Range Interval Problem

### ISSUE THREAD

**Issue by cknivu** [acconeer/acconeer-python-exploration#104]
**Describe the bug**
The GUI stops when I increase the range interval[m]

**To reproduce**
1. Start the GUI
2. Click on Scan Control >Envelope
3. Set Range intervall [m] from 0,20 - 5,00
4. The GUI stops 

**Traceback**
```
C:\Users\Kochc\Desktop>python  C:\Users\Kochc\Downloads\acconeer-python-exploration-master\gui\main.py
12:55:56.133 | INFO    | MainProcess      | acconeer.exptool.clients.base        | reported version: 2.10.0
12:56:08.642 | INFO    | MainProcess      | acconeer.exptool.clients.reg.client  | data length: 9912
12:56:08.643 | INFO    | MainProcess      | acconeer.exptool.clients.reg.client  | buffer size: 19824 B
12:56:08.644 | INFO    | MainProcess      | acconeer.exptool.clients.reg.client  | requested data rate: 0.79 Mbit/s
12:56:09.156 | WARNING | MainProcess      | acconeer.exptool.clients.reg.client  | successfully recovered from corrupt frame
```
**Screenshots**
![grafik](https://user-images.githubusercontent.com/99403131/153407762-32f56fdd-01a8-43ee-b78f-e891368688b7.png)

**Environment (please complete the following information):**
 - Host OS: Windows 10
 - Acconeer hardware: XM112 + XB112
 - Acconeer software version: RSS v2.10.0
 - Exploration version: v3.16.1

**Additional context**
N/A

**Comment by AndersBuhl** [comment]
Hi,

I was unable to reproduce this. You can try two things:

1. Untick the the box "Limit" for the update rate setting
2. Reset all settings to default, by pressing default. Only change the range settings and see if it works.

Br,
Anders
