### ISSUE TITLE
Non-radial speed measurement

### ISSUE THREAD

**Issue by bulbulbahar** [acconeer/acconeer-python-exploration#109]
Hello,
I am using XM112 Module together with XB112 Breakout board. I am trying to do some speed measurements.

I would like to somehow measure the speed of a treadmill. I know from here, [Speed (sparse)](https://docs.acconeer.com/en/latest/processing/speed_sparse.htmll) , " a speed estimate of a target’s radial speed from or towards the sensor" is possible. But could it be somehow possible to measure the speed of the treadmill, with a setup like in the below picture?
![165779186-1b29eed9-01dd-4e20-a162-3822bc283bf6](https://user-images.githubusercontent.com/44210691/165781338-07e8c21d-3997-432b-a6da-376d270778fe.png)

So my question would be, to what extent a velocity measurement is possible laterally or at an angle to the target and is it possible measure the speed of a system like this at all with radar technology? Thanks in advance.

Cheers, 
Bahar

**Comment by vackraetraed** [comment]
Hello @bulbulbahar 

Our first impression is that this would be very hard to do.
The radar would have to be in an angle and pick up on irregularities of the rubber band perhaps when it is moving.
Though the radar might even shine through the rubber and bounce off the treadmill itself.
Also, you would have to find some way to filter out the movement of feet and legs, possibly by shielding the radar.
Then there might also be some noise from the machine shaking when someone is actually running on it.

We do not want to say it is impossible though, just that we would consider it very hard with a low chance of success.

**Comment by bulbulbahar** [comment]
Hello @vackraetraed, thanks for the answer. 
Let's assume there won't be anyone running, the treadmill will be empty.
Or we can also consider a conveyor belt which is actually basically the same thing.
You said, it is not impossible but really hard. I would like to ask what would be the perfect conditions also the perfect sensor software settings in order to get at least some kind of promising results?

**Comment by vackraetraed** [comment]
Hello @bulbulbahar 

I just want to point out that I said "We do not want to say it is impossible", but it might be.
First of all you should verify that you can actually see something with the rubber band.
Try starting the exploration tool with sparse on profile 2 and analyze the data if you can see any kind of moment that does not look like noise.

**Comment by bulbulbahar** [comment]
Hi @vackraetraed,
I did some measurements today, and the radar actually ouputs a constant speed result. Even though it is not the actual speed of the band, it is still some persistent speed result which gave me some hope. You can see it below.
![Capture](https://user-images.githubusercontent.com/44210691/166923069-7d08a2f6-ef3b-42c6-bc66-2f53ac65b7df.PNG)

 I tried out some different setting configurations and the constant value I get also changed but its still not the actual speed of the band. I am wondering was it just a coincidence or it needs really good config calibration. Thanks a lot for your time anyway :)

**Comment by vackraetraed** [comment]
Hello @bulbulbahar 

I do not think the speed example would be of much use in this example.
There is really no telling what it actually looks at.
You would probably have to develop something new from the sparse data.
That is why I suggested looking at the data from the sparse service instead.

I think there are easier ways to sense speed of the treadmill than using our radar.

**Comment by bulbulbahar** [comment]
@vackraetraed Thanks for the help!
