### ISSUE TITLE
Envelope 3d Demo

### ISSUE THREAD

**Issue by Ryanstak** [acconeer/acconeer-python-exploration#110]
![fig_env_demo](https://user-images.githubusercontent.com/101952965/167280309-694380ef-2025-4f84-b6c0-ffbb6cce5dbd.png)

This image is in the introduction section and it states that this is the output of the envelope service in the exploration tool. Mine doesn't look like that. Am I missing a setting or something?
![Exptool_Envelope](https://user-images.githubusercontent.com/101952965/167280462-a51d42fc-a29c-41fc-baa4-fd4add975199.png)

**Comment by AndersBuhl** [comment]
Hi,

The 3D version of envelope was removed in 4.0.0. It is still available in the Radar Viewer if you checkout the v3-branch.

**Comment by AndersBuhl** [comment]
Hi,

My mistake, it was removed earlier. This is the last commit containing the radar_viewer 1d4069bf71d21cde91ffd1e6074f73df3258f0d8. Please checkout that and find the radar viewer folder in the root.

**Comment by Ryanstak** [comment]
Thank you. Is there anyway to get the metadata from the 3d demo, or is it just a live view?

Thanks,

Ryan Stakenborghs
Stak Information Consultation

**Comment by AndersBuhl** [comment]
Hi,

It is only meant for a live view. To get more in-depth data, please refer to the exploration tool GUI and example scripts.

**Comment by Ryanstak** [comment]
If I wanted to create a module that displayed a graph similar to the distance detector, but in 3d. Would pyqtgraph or matplotlib be better for this? It looks like both have the capability.
