### ISSUE TITLE
Exploration Tool on Raspberry Pi with PySide 6

### ISSUE THREAD

**Issue by chadrockey** [acconeer/acconeer-python-exploration#112]
The old exploration tool ran great on the same raspberry pi running the streaming server.

It seems that qt6 and pyside6 aren’t yet supported on raspberry pi.  Is there any alternative?

Is running the streaming server on the raspberry pi a feature you would like to preserve?  Or was that ability mostly unintended?

**Comment by chadrockey** [comment]
Also, does the main readme need to be adjusted?  It seems like PySide6 is also not supported for Ubuntu 18.04

**Comment by AndersBuhl** [comment]
Hi,

Running the GUI on a raspberry is not possible, but you can install and run the algo parts and run through python scripts.

**Comment by AndersBuhl** [comment]
Hi,

Thank you for your input!

We will update the instructions
