### ISSUE TITLE
acconeer.exptool.a111._clients.base.ClientError: already streaming

### ISSUE THREAD

**Issue by Asaad7777** [acconeer/acconeer-python-exploration#117]
I received the following error while trying to run acconeer code. How I can solve the problem?
![erroe](https://user-images.githubusercontent.com/109267857/178910646-e376ae38-6162-4987-95ec-9eb9d1a7547d.PNG)

**Comment by AndersBuhl** [comment]
Hi,

Could you please show the code you are running?

BR,
Anders
