### ISSUE TITLE
Could Not Open Port : PermissionError 'Access is denied'

### ISSUE THREAD

**Issue by JCJC7** [acconeer/acconeer-python-exploration#120]
Hi, I've recently purchased the Acconeer XE132 kit and try some of its functions. I have tried the GUI to get the basic idea of the radar services. I also successfully run the python scripts for the basic services as guided in the github page (except IQ services as it shows that IQ mode is not supported). However, when I try to run the python code for **sparse_fft** which I downloaded from github, it pops out this error. Here I would like to seek for solution to this error in the below figure. Thank you in advance. 

![2022-11-03_14-30-52](https://user-images.githubusercontent.com/117339457/199862843-f259777b-b8f4-44dd-968c-067566ba871d.jpg)

**Comment by stijnb1234** [comment]
_(Your Windows username is still visible)_

Make sure the module is connected to COM8 and that COM8 is not used by anything else.

**Comment by JCJC7** [comment]
Hi, thank you for the reply.
Yes, I'm sure that the module is connected to COM8. This is the figure for envelope python script. 
![image](https://user-images.githubusercontent.com/117339457/199880018-3bbf6690-63d5-4d66-8b9f-2721817b84eb.png)

If I run the **sparse_fft** __main__.py script, the same error still occurs.
I tried with other algorithm python scripts, it is all showing the same error. Did I do something wrong or I need to do something before running these scripts?  

path : ...\github-acconeer-python-exploration-master\src\acconeer\exptool\a111\algo
![image](https://user-images.githubusercontent.com/117339457/199880661-758f104c-2abb-4bb4-b716-f4312119cff2.png)

**Comment by vackraetraed** [comment]
Hello,

It seems to work fine for me to run these algo examples on Linux, however, when running the same code on Windows I get the same error as you. 
So might be some Windows specific permission that is not granted when running the algorithms standalone like this.
Perhaps there is some clue in the differences when establishing a UART connection in the standalone examples vs the standalone algo ones.

**Comment by vackraetraed** [comment]
Could you try running the firmware from the algo map with the following command:
python -m sparse_fft -u COM8

**Comment by vackraetraed** [comment]
Perhaps I meant the sparse_fft map :D

**Comment by vackraetraed** [comment]
Sorry, I questioned myself too much.
You should write the command in the algo folder, I was correct the first time.

**Comment by vackraetraed** [comment]
You can also try:
python -m acconeer.exptool.a111.algo.sparse_fft -u COM8

From any folder if you have installed the package.

**Comment by JCJC7** [comment]
Thank you for your support! The final command works!. 

<img width="667" alt="whole_file" src="https://user-images.githubusercontent.com/117339457/200346017-49c7158e-c49a-45bb-a08a-7013b1a6f6ac.png">

Truly appreciate your time and effort. Thank you!
