### ISSUE TITLE
XE132 IQ Mode Not Supported

### ISSUE THREAD

**Issue by JCJC7** [acconeer/acconeer-python-exploration#121]
Hi, I want to get clarification regarding the services available on XE132. After reading the official documentation, I realized the IQ mode is available for Acconeer A111 sensor. However, when I try to run IQ service on my XE132, it shows that the mode is not supported by this module. Hence, I would like to seek for clarification to check if XE132 indeed does not support IQ mode or I missed out something during the installation process resulting this issue occurs. Thank you in advance. 
[ I have run other 3 modes and all of them work fine ]   
![image](https://user-images.githubusercontent.com/117339457/201006879-9762f867-6963-4c76-8439-278bd400d598.png)

**Comment by vackraetraed** [comment]
XM132 (the module on XE132) does not support IQ.
So it is not surprising that you get this message.
