### ISSUE TITLE
Errors for XM112-XB112 in personalized GUI on RaspberryPi ubuntu

### ISSUE THREAD

**Issue by Batmannilsson** [acconeer/acconeer-python-exploration#131]
I've created my own GUI using PySimpleGUI (psg) and I'm running it with mixed success on a raspberry pi 4B (8GB) with ubuntu 22.04 LTS. The program also works with similar success on windows (where it was built) built with minimal changes with regards to the resolution of the UI windows. The program usually successfully start plotting, then after some time it states that it has "successfully recovered from a corrupt frame"without the live plot suffering. After this the program eventually runs into this error:

Traceback (most recent call last):
  File "/path/to/GUI-folder/sensor.py", line 41, in <module>
    data_info, data = client.get_next()
  File "/path/to/venv/lib/python3.9/site-packages/acconeer/exptool/a111/_clients/client.py", line 143, in get_next
    return self.subclient.get_next()
  File "/path/to/venv/lib/python3.9/site-packages/acconeer/exptool/a111/_clients/base.py", line 158, in get_next
    return self._get_next()
  File "/path/to/venv/lib/python3.9/site-packages/acconeer/exptool/a111/_clients/reg/client.py", line 256, in _get_next
    packet = self._recv_packet(allow_recovery_skip=True)
  File "/path/to/venv/lib/python3.9/site-packages/acconeer/exptool/a111/_clients/reg/client.py", line 399, in _recv_packet
    raise ClientError("got invalid frame and could not recover")
acconeer.exptool.a111._clients.base.ClientError: got invalid frame and could not recover

It's able to recover  by restarting the animation through the GUI but it eventually runs into it again and again with random intervalls. Does anyone know the general cause for this? Or, an admittedly harder question, is there anything specific i should change in my code?

**To reproduce**
Due to my limited knowledge of the functionalities of the exptool package and how to marry it with my own GUI in psg, I've gone about plotting the sensors incoming data in an ad-hoc way. Instead of collecting the data and creating lists all in the same file I'm continuously storing and overwriting the data in a separate txt-file and simultaneously reading the file to create lists for plotting. I know this is far from ideal and I'm working on better methods but in the interest of having a working product soon I'll have to invest in this method.

I've attached a folder with the necessary files to run the program. The file "GUI-with-sensor.py" is he main program to run. The file "sensor.py" is for preparing and taking in data from the sensor. "command.txt" is used to to tell the program to either "Start" or "stop" and "state.txt" is used to tell that the program is "ready" to start a measurement or "done" taking one. So before a measurement they will read "stop" & "done", then after starting they will read "start" & "ready" and after stopping a measurement they will again say "stop" & "done". The "settings.txt" is for storing the measuring distance interval and "output.txt" is the file for storing every new set of intensities

1. Make sure all files are in the same environment
2. Make sure command.py reads "stop" and stade.py reads "done" 
3. Start GUI-with-sensor.py
4. Press the "Start" button in the GUI and let the program run for some time until the error eventually occurs

**Installed packages**
acconeer-exptool==7.2.0
altgraph==0.17.3
argcomplete==2.1.2
attrs==23.1.0
beautifulsoup4==4.12.2
bleach==6.0.0
bs4==0.0.1
build==0.9.0
certifi==2023.5.7
cffi==1.15.1
charset-normalizer==3.1.0
cloudpickle==2.2.1
colorlog==6.7.0
commonmark==0.9.1
contourpy==1.1.0
cryptography==41.0.1
cycler==0.11.0
darkdetect==0.7.1
distlib==0.3.6
docutils==0.20.1
doit==0.34.2
filelock==3.12.2
fonttools==4.40.0
future==0.18.3
h5py==3.9.0
idna==3.4
importlib-metadata==6.7.0
importlib-resources==5.12.0
iso8601==2.0.0
jaraco.classes==3.2.3
jeepney==0.8.0
keyring==24.2.0
kiwisolver==1.4.4
matplotlib==3.7.1
more-itertools==9.1.0
nox==2022.11.21
numpy==1.25.0
packaging==23.1
pep517==0.13.0
Pillow==9.5.0
pkginfo==1.9.6
platformdirs==3.8.0
psutil==5.9.5
pycparser==2.21
Pygments==2.15.1
pyinotify==0.9.6
pyinstaller==5.13.0
pyinstaller-hooks-contrib==2023.4
pyparsing==3.1.0
pyperclip==1.8.2
pyqtdarktheme==2.1.0
pyqtgraph==0.13.3
pyserial==3.5
PySide6==6.4.3
PySimpleGUI==4.60.5
python-dateutil==2.8.2
pyusb==1.2.1
PyYAML==6.0
QtAwesome==1.2.3
QtPy==2.3.1
readme-renderer==40.0
requests==2.31.0
requests-toolbelt==1.0.0
rfc3986==2.0.0
rich==12.6.0
scipy==1.11.1
SecretStorage==3.3.3
shiboken6==6.4.3
shiboken6-generator==6.4.3
six==1.16.0
soupsieve==2.4.1
textual==0.1.18
tomli==2.0.1
twine==4.0.1
typing_extensions==4.7.0
urllib3==2.0.3
virtualenv==20.23.1
webencodings==0.5.1
zipp==3.15.0

 - Host OS: Ubuntu 20.04
 - Acconeer hardware: Raspberry Pi 4B (8GB) XM112+XB112
 - Acconeer software version: 2.14.2
 - Exploration version:7.2.0

[GUI.zip](https://github.com/acconeer/acconeer-python-exploration/files/11999540/GUI.zip)

**Comment by AndersBuhl** [comment]
Hi,

Corrupt frames can often happen when the load on the system is high, so reading and writing to a file is not ideal in this case.

My suggestion is to try to run a configuration with a low update rate, e.g. 10 Hz, to reduce the load on the system. This might give some more indications on what is happening.

BR,
Anders
