### ISSUE TITLE
Exploration tool crashes

### ISSUE THREAD

**Issue by sebglatz** [acconeer/acconeer-python-exploration#135]
**Describe the bug**
`python -m acconeer.exptool.app` opens the GUI.
But when clicking the A121 window the GUI crashes.
(Would not happen when clicking the A111 window)

**Traceback**
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/seb/.local/lib/python3.10/site-packages/acconeer/exptool/app/__main__.py", line 11, in <module>
    from .new import main
  File "/home/seb/.local/lib/python3.10/site-packages/acconeer/exptool/app/new/__init__.py", line 13, in <module>
    from .app import main
  File "/home/seb/.local/lib/python3.10/site-packages/acconeer/exptool/app/new/app.py", line 24, in <module>
    from .ui import AppModelViewer, MainWindow
  File "/home/seb/.local/lib/python3.10/site-packages/acconeer/exptool/app/new/ui/__init__.py", line 4, in <module>
    from . import components, icons, utils
  File "/home/seb/.local/lib/python3.10/site-packages/acconeer/exptool/app/new/ui/components/__init__.py", line 4, in <module>
    from . import a121, pidgets
  File "/home/seb/.local/lib/python3.10/site-packages/acconeer/exptool/app/new/ui/components/a121/__init__.py", line 7, in <module>
    from .sensor_config_editor import SensorConfigEditor
  File "/home/seb/.local/lib/python3.10/site-packages/acconeer/exptool/app/new/ui/components/a121/sensor_config_editor.py", line 19, in <module>
    from acconeer.exptool.app.new.ui.components.json_save_load_buttons import (
  File "/home/seb/.local/lib/python3.10/site-packages/acconeer/exptool/app/new/ui/components/json_save_load_buttons/__init__.py", line 4, in <module>
    from .buttons import (
  File "/home/seb/.local/lib/python3.10/site-packages/acconeer/exptool/app/new/ui/components/json_save_load_buttons/buttons.py", line 19, in <module>
    from acconeer.exptool.app.new.ui.icons import CHECKMARK, FOLDER_OPEN, SAVE
  File "/home/seb/.local/lib/python3.10/site-packages/acconeer/exptool/app/new/ui/icons.py", line 6, in <module>
    import qtawesome as qta
  File "/usr/local/lib/python3.10/dist-packages/qtawesome/__init__.py", line 19, in <module>
    from .iconic_font import IconicFont, set_global_defaults
  File "/usr/local/lib/python3.10/dist-packages/qtawesome/iconic_font.py", line 22, in <module>
    from qtpy.QtCore import QObject, QPoint, QRect, qRound, Qt
ImportError: cannot import name 'qRound' from 'qtpy.QtCore' (/home/seb/.local/lib/python3.10/site-packages/qtpy/QtCore.py)

**Installed packages**
acconeer-exptool @ file:///home/seb/acconeer-python-exploration
action-msgs==1.2.1
action-tutorials-interfaces==0.20.3
action-tutorials-py==0.20.3
actionlib-msgs==4.2.3
airium==0.2.5
ament-cmake-test==1.3.5
ament-copyright==0.12.8
ament-cppcheck==0.12.8
ament-cpplint==0.12.8
ament-flake8==0.12.8
ament-index-python==1.4.0
ament-lint==0.12.8
ament-lint-cmake==0.12.8
ament-package==0.14.0
ament-pep257==0.12.8
ament-uncrustify==0.12.8
ament-xmllint==0.12.8
angles==1.15.0
aniso8601==9.0.1
ansible-base==2.10.8
anyio==3.6.2
apache-libcloud==3.2.0
appdirs==1.4.4
apturl==0.5.2
aqtinstall==3.1.6
argcomplete==1.8.1
arghelper==0.4.2
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arm-gdb==0.9.9
arrow==1.2.3
astroid==2.9.3
async-lru==2.0.2
async-timeout==4.0.2
atomicwrites==1.4.1
attributes-doc==0.3.0
attrs==23.1.0
Babel==2.12.1
backcall==0.2.0
bcrypt==3.2.0
beautifulsoup4==4.10.0
beniget==0.4.1
bidict==0.22.1
bitstring==4.0.2
black==22.3.0
bleach==6.0.0
blessed==1.20.0
blinker==1.4
bmap-tools==3.6
Bottleneck==1.3.2
branca==0.6.0
Brlapi==0.8.3
Brotli==1.0.9
bs4==0.0.1
builtin-interfaces==1.2.1
cachelib==0.10.2
cachetools==5.3.0
catkin-pkg==0.5.2
catkin-pkg-modules==1.0.0
cbor2==5.5.1
certifi==2020.6.20
cffi==1.15.1
chardet==4.0.0
charset-normalizer==3.1.0
click==8.0.2
cloudpickle==2.2.1
cmsis-svd==0.4
cogapp==3.3.0
colcon-argcomplete==0.3.3
colcon-bash==0.4.2
colcon-cd==0.1.1
colcon-cmake==0.2.27
colcon-common-extensions==0.3.0
colcon-core==0.6.1
colcon-defaults==0.2.5
colcon-devtools==0.2.3
colcon-library-path==0.2.1
colcon-metadata==0.2.5
colcon-notification==0.2.15
colcon-output==0.2.13
colcon-package-information==0.3.3
colcon-package-selection==0.2.10
colcon-parallel-executor==0.2.4
colcon-pkg-config==0.1.0
colcon-powershell==0.3.7
colcon-python-setup-py==0.2.8
colcon-recursive-crawl==0.2.1
colcon-ros==0.3.21
colcon-test-result==0.3.8
colcon-zsh==0.4.0
colorama==0.4.4
colorlover==0.3.0
comm==0.1.3
command-not-found==0.3
commonmark==0.9.1
composition-interfaces==1.2.1
configobj==5.0.6
contourpy==1.2.0
coverage==7.2.5
cpplint==1.4.5
crc==5.0.0
cryptography==3.4.8
cupshelpers==1.0
cv-bridge==3.2.1
cycler==0.11.0
darkdetect==0.7.1
dash==2.6.0
dash-bootstrap-components==1.0.0
dash-core-components==2.0.0
dash-html-components==2.0.0
dash-mantine-components==0.12.1
dash-table==5.0.0
dbus-python==1.2.18
debugpy==1.6.7
decorator==4.4.2
defer==1.0.6
defusedxml==0.7.1
demo-nodes-py==0.20.3
diagnostic-msgs==4.2.3
diagnostic-updater==3.1.2
distlib==0.3.6
distro==1.7.0
distro-info==1.1+ubuntu0.1
dnspython==2.1.0
docker==6.1.2
docutils==0.20.1
doit==0.34.0
domain-coordinator==0.10.0
dronecan==1.0.25
duplicity==0.8.21
easywebdav==1.2.0
ecdsa==0.18.0
emdbg==1.3.3
empy==3.3.4
esptool==4.6.2
et-xmlfile==1.1.0
eventlet==0.33.3
evo==1.12.0
example-interfaces==0.9.3
examples-rclpy-executors==0.15.1
examples-rclpy-minimal-action-client==0.15.1
examples-rclpy-minimal-action-server==0.15.1
examples-rclpy-minimal-client==0.15.1
examples-rclpy-minimal-publisher==0.15.1
examples-rclpy-minimal-service==0.15.1
examples-rclpy-minimal-subscriber==0.15.1
exceptiongroup==1.1.1
fabric==2.6.0
fasteners==0.14.1
fastjsonschema==2.16.3
ffmpeg==1.4
flake8==4.0.1
Flask==2.1.3
Flask-Compress==1.13
Flask-Cors==3.0.10
flask-restx==1.1.0
Flask-Session==0.4.1
Flask-SQLAlchemy==2.5.1
Flask-WTF==1.1.1
folium==0.14.0
fonttools==4.29.1
fqdn==1.5.1
fs==2.4.12
future==0.18.2
gast==0.5.2
geographic-msgs==1.0.5
geographiclib==2.0
geometry-msgs==4.2.3
geopy==2.3.0
google-api-core==2.8.2
google-api-python-client==2.86.0
google-auth==2.18.0
google-auth-httplib2==0.1.0
google-auth-oauthlib==1.0.0
google-cloud-appengine-logging==1.3.0
google-cloud-audit-log==0.2.5
google-cloud-core==2.3.2
google-cloud-firestore==2.11.1
google-cloud-logging==3.5.0
google-cloud-secret-manager==2.11.0
google-cloud-storage==2.9.0
google-crc32c==1.5.0
google-resumable-media==2.5.0
googleapis-common-protos==1.56.4
gpiod==1.5.4
graphviz==0.20.1
greenlet==2.0.2
grpc-google-iam-v1==0.12.4
grpcio==1.54.2
grpcio-status==1.48.2
grpcio-tools==1.48.2
gunicorn==20.1.0
h3==3.7.6
h5py==3.8.0
html5lib==1.1
httplib2==0.20.2
humanize==4.6.0
idna==3.3
ifaddr==0.2.0
image-geometry==3.2.1
importlib-metadata==4.6.4
inflate64==0.3.1
iniconfig==2.0.0
inquirer==3.1.3
interactive-markers==2.3.2
invoke==1.7.3
ipykernel==6.23.1
ipython==7.31.1
isoduration==20.11.0
isort==5.4.2
itsdangerous==2.1.2
jdcal==1.0
jedi==0.18.0
jeepney==0.7.1
Jinja2==3.0.3
jmespath==0.10.0
joblib==1.2.0
json5==0.9.14
jsonpointer==2.3
jsonschema==4.17.3
jupyter-events==0.6.3
jupyter-lsp==2.1.0
jupyter_client==8.2.0
jupyter_core==5.3.0
jupyter_server==2.5.0
jupyter_server_terminals==0.4.4
jupyterlab==4.0.0
jupyterlab-pygments==0.2.2
jupyterlab_server==2.22.1
keyring==23.5.0
kiwisolver==1.3.2
language-selector==0.1
lark==1.1.1
laser-geometry==2.4.0
launch==1.0.4
launch-ros==0.19.6
launch-testing==1.0.4
launch-testing-ros==0.19.6
launch-xml==1.0.4
launch-yaml==1.0.4
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
lazy-object-proxy==1.9.0
lifecycle-msgs==1.2.1
llvmlite==0.38.0
lockfile==0.12.2
logging-demo==0.20.3
loguru==0.7.0
louis==3.20.0
lttb==0.3.1
lxml==4.8.0
lz4==3.1.3+dfsg
macaroonbakery==1.3.1
Mako==1.1.3
map-msgs==2.1.0
Markdown==3.4.3
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.8.2
matplotlib-inline==0.1.3
mcap==1.0.2
mcap-ros2-support==0.3.0
mccabe==0.6.1
mdurl==0.1.2
meld==3.20.4
meson==0.61.2
message-filters==4.3.3
methodtools==0.4.7
mistune==2.0.5
mock==4.0.3
modality==0.1.0
monotonic==1.6
more-itertools==8.10.0
mpi4py==3.1.3
mpmath==0.0.0
msal==1.22.0
multivolumefile==0.2.3
mypy-extensions==1.0.0
natsort==8.3.1
nav-msgs==4.2.3
nbclient==0.7.4
nbconvert==7.4.0
nbformat==5.8.0
nest-asyncio==1.5.6
netaddr==0.8.0
netifaces==0.11.0
nose==1.3.7
notebook_shim==0.2.3
notify2==0.3.1
ntlm-auth==1.4.0
numba==0.55.1
numexpr==2.8.1
numpy==1.24.3
numpy-stl==3.0.1
oauth2client==4.1.3
oauthlib==3.2.0
odfpy==1.4.2
olefile==0.46
openpyxl==3.1.2
osrf-pycommon==2.0.2
packaging==21.3
pandas==2.0.1
pandocfilters==1.5.0
paramiko==2.9.3
parso==0.8.1
patch==1.16
pathlib==1.0.1
pathlib2==2.3.7.post1
pathspec==0.9.0
pbr==5.8.0
pcl-msgs==1.0.0
pendulum-msgs==0.20.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.0.1
platformdirs==3.5.1
plotly==5.14.1
pluggy==1.0.0
plumbum==1.8.2
ply==3.11
prettytable==3.7.0
prometheus-client==0.16.0
prompt-toolkit==3.0.28
proto-plus==1.19.6
protobuf==3.15.6
psutil==5.9.0
ptyprocess==0.7.0
py==1.10.0
py7zr==0.20.5
pyasn1==0.5.0
pyasn1-modules==0.3.0
pybcj==1.0.1
pycairo==1.20.1
pycodestyle==2.8.0
pycparser==2.21
pycryptodomex==3.11.0
pycups==2.0.1
pydocstyle==6.1.1
pydot==1.4.2
PyDrive==1.3.1
pydwf==1.1.19
pyFFTW==0.13.1
pyflakes==2.4.0
pyftdi==0.54.0
pygdbmi==0.11.0.0
Pygments==2.16.1
PyGObject==3.42.1
pyinotify==0.9.6
PyJWT==2.3.0
pykerberos==1.1.14
pylint==2.12.2
pymacaroons==0.13.0
pymavlink==0.0.0
pymonocypher==3.1.3.2
PyNaCl==1.5.0
pyOpenSSL==21.0.0
pyparsing==2.4.7
pyperclip==1.8.2
pyppmd==1.0.0
PyQt5==5.15.6
PyQt5-Qt5==5.15.2
PyQt5-sip==12.13.0
pyqtdarktheme==2.1.0
pyqtgraph==0.13.3
pyRFC3339==1.1
pyros-genmsg==0.5.8
pyrsistent==0.19.3
pyrtcm==0.1.8
pyserial==3.5
PySide6==6.6.1
PySide6-Addons==6.6.1
PySide6-Essentials==6.6.1
pytest==7.2.1
pytest-check==2.1.4
pytest-cov==4.0.0
pytest-repeat==0.9.1
pytest-rerunfailures==11.1.2
python-apt==2.4.0+ubuntu2
python-dateutil==2.8.2
python-debian==0.1.43+ubuntu1.1
python-editor==1.0.4
python-engineio==4.3.0
python-json-logger==2.0.7
python-qt-binding==1.1.1
python-socketio==5.5.0
python-utils==3.5.2
pythran==0.10.0
pytz==2022.1
pyuavcan-v0==1.0.0.dev35
pyulog==1.0.1
pyusb==1.2.1
pywinrm==0.3.0
pyxdg==0.27
PyYAML==5.4.1
pyzmq==25.0.2
pyzstd==0.15.7
qt-dotgraph==2.2.2
qt-gui==2.2.2
qt-gui-cpp==2.2.2
qt-gui-py-common==2.2.2
QtAwesome==0.3.3
qtconsole==4.2.1
QtPy==2.4.1
qtwidgets==1.1
quality-of-service-demo-py==0.20.3
randomproto==0.0.1
rcl-interfaces==1.2.1
rclpy==3.3.10
rcutils==5.1.3
readchar==4.0.5
reedsolo==1.7.0
regex==2023.5.5
reportlab==3.6.8
requests==2.30.0
requests-kerberos==0.12.0
requests-ntlm==1.1.0
requests-oauthlib==1.3.1
requests-toolbelt==0.9.1
resource-retriever==3.1.1
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==12.6.0
rmw-dds-common==1.6.0
roman==3.3
ros2action==0.18.7
ros2bag==0.15.8
ros2cli==0.18.7
ros2component==0.18.7
ros2doctor==0.18.7
ros2interface==0.18.7
ros2launch==0.19.6
ros2lifecycle==0.18.7
ros2multicast==0.18.7
ros2node==0.18.7
ros2param==0.18.7
ros2pkg==0.18.7
ros2run==0.18.7
ros2service==0.18.7
ros2topic==0.18.7
rosbag2-interfaces==0.15.8
rosbag2-py==0.15.8
rosdep==0.22.2
rosdep-modules==0.22.2
rosdistro-modules==0.9.0
rosgraph-msgs==1.2.1
rosidl-adapter==3.1.5
rosidl-cli==3.1.5
rosidl-cmake==3.1.5
rosidl-generator-c==3.1.5
rosidl-generator-cpp==3.1.5
rosidl-generator-py==0.14.4
rosidl-parser==3.1.5
rosidl-runtime-py==0.9.3
rosidl-typesupport-c==2.0.1
rosidl-typesupport-cpp==2.0.1
rosidl-typesupport-fastrtps-c==2.2.1
rosidl-typesupport-fastrtps-cpp==2.2.1
rosidl-typesupport-introspection-c==3.1.5
rosidl-typesupport-introspection-cpp==3.1.5
rospkg-modules==1.5.0
rpyc==5.3.1
rpyutils==0.2.1
rqt-action==2.0.1
rqt-bag==1.1.4
rqt-bag-plugins==1.1.4
rqt-console==2.0.2
rqt-graph==1.3.0
rqt-gui==1.1.5
rqt-gui-py==1.1.5
rqt-msg==1.2.0
rqt-plot==1.1.2
rqt-publisher==1.5.0
rqt-py-common==1.1.5
rqt-py-console==1.0.2
rqt-reconfigure==1.1.1
rqt-service-caller==1.0.5
rqt-shell==1.0.2
rqt-srv==1.0.3
rqt-topic==1.5.0
rsa==4.9
scikit-learn==1.2.2
scipy==1.11.0
seaborn==0.12.2
SecretStorage==3.3.1
selinux==3.3
semantic-version==2.10.0
Send2Trash==1.8.2
sensor-msgs==4.2.3
sensor-msgs-py==4.2.3
shape-msgs==4.2.3
shiboken6==6.6.1
simplejson==3.17.6
six==1.16.0
sniffio==1.3.0
snowballstemmer==2.2.0
sortedcontainers==2.4.0
soupsieve==2.3.1
SQLAlchemy==1.4.31
sros2==0.10.4
statistics-msgs==1.2.1
std-msgs==4.2.3
std-srvs==4.2.3
stereo-msgs==4.2.3
symengine==0.10.0
sympy==1.9
systemd-python==234
tables==3.7.0
tabulate==0.8.9
teleop-twist-keyboard==2.3.2
tenacity==8.2.2
termcolor==2.3.0
terminado==0.17.1
terminator==2.1.1
texttable==1.6.7
textual==0.1.18
tf-transformations==1.0.0
tf2-geometry-msgs==0.25.4
tf2-kdl==0.25.4
tf2-msgs==0.25.4
tf2-py==0.25.4
tf2-ros-py==0.25.4
tf2-tools==0.25.4
threadpoolctl==3.1.0
timezonefinder==6.0.2
tinycss2==1.2.1
toml==0.10.2
tomli==2.0.1
topic-monitor==0.20.3
tornado==6.3.2
tqdm==4.65.0
traitlets==5.9.0
trajectory-msgs==4.2.3
transforms3d==0.4.1
transitions==0.9.0
turtlesim==1.4.2
typing_extensions==4.2.0
tzdata==2023.3
ubuntu-advantage-tools==8001
ubuntu-drivers-common==0.0.0
ufoLib2==0.13.1
ufw==0.36.1
unattended-upgrades==0.1
unicodedata2==14.0.0
unique-identifier-msgs==2.2.1
uri-template==1.2.0
uritemplate==4.1.1
urllib3==1.26.5
usb-creator==0.3.7
visualization-msgs==4.2.3
wadllib==1.3.6
wcwidth==0.2.5
webcolors==1.13
webencodings==0.5.1
websocket-client==1.5.1
Werkzeug==2.3.7
wirerope==0.4.7
wrapt==1.13.3
WTForms==3.0.1
wxPython==4.2.0
xdg==5
xkit==0.0.0
xlwt==1.3.0
xmltodict==0.12.0
yamllint==1.26.3
yoctopuce==1.10.55677
zeroconf==0.39.0
zipp==1.0.0
zstandard==0.21.0

**Environment (please complete the following information):**
 - Host OS: Ubuntu 22.04.3 LTS
 - Acconeer hardware: XE125 (But GUI crashes independently of connected HW)
 - Exploration version: v7.7.3

**Comment by vackraetraed** [comment]
Most Exploration Tool errors related to GUI is usually related to a new version of PySide6, I would recommend trying:
python -m pip install PySide6==6.4.3

Best regards,
Anton

**Comment by sebglatz** [comment]
This pyside6 version caused another crash on my system.
But a clean install inside virtualenv with python version 3.11.5 solves the problem (pyside 6.6.1 and exptool 7.7.3)
