### ISSUE TITLE
I2C error

### ISSUE THREAD

**Issue by hariiiis** [acconeer/acconeer-python-exploration#158]
I have flashed the i2c_distance_detector binary to my XM125 (on the XE125 board) and I am trying to communicate with the sensor.

I have asserted the WAKEUP pin and I correctly configured the sensor address at 0xa2 (since I grounded the I2C-ADDR pin).

I am waiting for the MCU-INT to be high before attempting communication.

However, I always get this reply when trying to read from the status register: 0x10040003
which indicates that there is an error with the sensor. (#define DISTANCE_REG_DETECTOR_STATUS_FIELD_DETECTOR_ERROR_MASK 0x10000000)

I must be missing something, any ideas?

(I realized this might be the wrong place for this question but I couldn't find a better one)

thanks

**Comment by jbjornstedt** [comment]
This is not a problem with the Acconeer Exploration Tool application.
Please file a ticket on our Customer Helpdesk if you need more assistance: https://support.acconeer.com/support/solutions

Best Regards,
Johan
