### ISSUE TITLE
Error with displaying GUI (couldn't connect to MK112 board via serial communication) 

### ISSUE THREAD

**Issue by msallmen23** [acconeer/acconeer-python-exploration#21]
I keep getting the following message when trying to run GUI. Please view the picture attached. 

Let me know if anyone has any ideas on how to fix this.

I have tried the following:
- installed python 3.6
- uninstalled all other versions of python
- used PuTTy to verify USB port knows MK112 board is connected
- Tried to make virtual environment for python using visual studio. (I still get the same error)
Please follow this Link:  https://ezgif.com/image-to-datauri/ezgif-3-a90847167c7a.png 

Picture:  ![gui_pic](https://user-images.githubusercontent.com/20482112/70503822-4af1f480-1af2-11ea-8936-184ec30e3358.png)

**Comment by dj-acconeer** [comment]
Could you verify that COM3 disappears when you unplug the module?

**Comment by msallmen23** [comment]
![image](https://user-images.githubusercontent.com/20482112/70504801-81c90a00-1af4-11ea-949c-8642fccc1018.png)

**Comment by msallmen23** [comment]
It's not showing up. Or where you referring to COM3 showing up on the GUI?

**Comment by dj-acconeer** [comment]
In order to help you best, I need to understand your setup.
First step is to make sure that the USB module is actually on COM3.
Are you running this in a VM or directly in Windows?

**Comment by msallmen23** [comment]
Directly on Windows. It is on COM3. 
![image](https://user-images.githubusercontent.com/20482112/70512925-97dbc800-1afe-11ea-8dd0-41605a057144.png)

**Comment by msallmen23** [comment]
Thanks for the assistance thus far.

**Comment by dj-acconeer** [comment]
From your other screenshot I can see that you are using the latest exploration tool with API 2.0.
We just released this new API version last week and there might be incompatibility issues.
When did you flash the software for the usb module?

**Comment by msallmen23** [comment]
Last week. Should I install previous version? If so, can you provide link to previous version that you recommend for my current enviornment.

**Comment by dj-acconeer** [comment]
I think first we could try to flash the usb module gain to make sure it's the latest.

**Comment by msallmen23** [comment]
What do you mean by flash the usb module?? I apologize I am a newbie to RF.

**Comment by dj-acconeer** [comment]
No problem. We will guide you through it.
Follow the instructions here to flash the latest firmware to the USB module

https://acconeer-python-exploration.readthedocs.io/en/latest/evk_setup/xm112.html

**Comment by msallmen23** [comment]
![image](https://user-images.githubusercontent.com/20482112/70514455-ae375300-1b01-11ea-9894-d13312182790.png)

**Comment by msallmen23** [comment]
Thank you

**Comment by msallmen23** [comment]
I ran the first script in the link you provided and that was the previous screenshot

**Comment by dj-acconeer** [comment]
That means, the srcipt found a device attache to com3.
If you could download bossa and the latest firmware and flash that to your module, we can make sure you have the latest firmware on the module.

**Comment by msallmen23** [comment]
ok, I am not able to download the link provided...

**Comment by msallmen23** [comment]
![image](https://user-images.githubusercontent.com/20482112/70514973-88f71480-1b02-11ea-9184-cee3aa6c4627.png)

**Comment by msallmen23** [comment]
the module sw user guide doesn't upload for me

**Comment by msallmen23** [comment]
I am on the Acconeer Developer site and am looking for that same "module software user guide". Can you point me in the right direction from the website?

**Comment by msallmen23** [comment]
Thanks again for all your help. I really appreciate it.

**Comment by dj-acconeer** [comment]
I looks like the link is outdated.
You need to go to our homepage at
https://developer.acconeer.com
Navigate to the "Developer" section and create an account.
Then login here
https://developer.acconeer.com/log-in/
and download the latest software.

**Comment by msallmen23** [comment]
Is this the right one?
![image](https://user-images.githubusercontent.com/20482112/70515223-facf5e00-1b02-11ea-96c3-3dee5b00975b.png)

**Comment by dj-acconeer** [comment]
Yes.

**Comment by msallmen23** [comment]
Ok, great.

**Comment by msallmen23** [comment]
![image](https://user-images.githubusercontent.com/20482112/70516403-f5731300-1b04-11ea-8f29-c7c682c46a1d.png)

**Comment by msallmen23** [comment]
THat is the new error that I am getting.

**Comment by msallmen23** [comment]
Should I try this as well? 
![image](https://user-images.githubusercontent.com/20482112/70516805-9b268200-1b05-11ea-8787-3d4f65414f18.png)

**Comment by msallmen23** [comment]
Nevermind, it is letting me write now. I had to perform a read first. Now it's letting me write.  
![image](https://user-images.githubusercontent.com/20482112/70517133-1c7e1480-1b06-11ea-8a21-a447a52238c9.png)

**Comment by msallmen23** [comment]
![image](https://user-images.githubusercontent.com/20482112/70518250-0b360780-1b08-11ea-88ac-4a0cc4f90589.png)

**Comment by msallmen23** [comment]
![image](https://user-images.githubusercontent.com/20482112/70518273-125d1580-1b08-11ea-9b03-befc92fb2b27.png)

**Comment by msallmen23** [comment]
This is the error that I am getting now.

**Comment by dj-acconeer** [comment]
In your screenshot, it looks like you flashed the bossac.exe to the USB module.
Make sure you select the firmware image you downloaded.
When you have flashed, you might have to unplug and plug back in the module.

**Comment by msallmen23** [comment]
![image](https://user-images.githubusercontent.com/20482112/70520683-efccfb80-1b0b-11ea-8a65-b8dbeefed7a1.png)

**Comment by msallmen23** [comment]
Ok, that was all that I installed from BOSSA. I will check again. THanks again for the feedback. I got the Bossa GUI to write successfully, however I will verify it is right firmware. I will take sc of that.

**Comment by msallmen23** [comment]
still getting the same error.

**Comment by dj-acconeer** [comment]
What is the name of the file that you flashed?

**Comment by msallmen23** [comment]
bossa-dpinst.wxs

**Comment by msallmen23** [comment]
It said it was windows driver signature in github repository. However I am sure that is not the right file. I tried searching for a .bin file in the Bossa 1.9.1 and couldn't find one.

**Comment by msallmen23** [comment]
![image](https://user-images.githubusercontent.com/20482112/70530852-c3bc7500-1b21-11ea-97fa-daee828e3a5a.png)

**Comment by dj-acconeer** [comment]
Please  download this file

acconeer_xm112_module_software_v2_0_0.zip

on the developer page labeled as

acconeer_xm112_module_software

From this zip file, please extract the binary

acc_module_server_xm112.bin

Then flash that file to your module.

**Comment by msallmen23** [comment]
Ok, thank you. I will try this.

**Comment by msallmen23** [comment]
I did precisely that and I am still getting the same issue.  
![image](https://user-images.githubusercontent.com/20482112/70535369-f9b22700-1b2a-11ea-97dc-8cbf84715645.png)

**Comment by dj-acconeer** [comment]
![image](https://user-images.githubusercontent.com/46452411/70535513-84137e80-1b5d-11ea-99fd-0e40a53ffff5.png)

It should look something like this.
And after flashing, unplug the module and plug it back in.

**Comment by dj-acconeer** [comment]
Do you still have issues with this?

**Comment by dj-acconeer** [comment]
Closing this for now
