### ISSUE TITLE
Power transmitted

### ISSUE THREAD

**Issue by lucassbroto** [acconeer/acconeer-python-exploration#28]
Hello!

I have a simple question for one of my projects:

I am using XM112 and XB112 in my scans and I am looking to evaluate the RCS in comparison to the number of pixes in an image, to create a "radar mask".

But to calculate the RCS from my measurement I'd like to know what is the power transmitted by the radar?

**Comment by dj-acconeer** [comment]
If you want to measure the RCS in absolute values, you might need to get a spectrum analyzer.
The transmitted power depends on many variables that we do not  have control over, such as your particular sensor integration.

An easier method might be to measure the reflected power from a corner reflector (or some other object with a well defined RCS)  and derive the transmitted power from that.
Now you can get a relative approximation with respect to that reference measurement.
