### ISSUE TITLE
Recv queue timeout

### ISSUE THREAD

**Issue by sembree** [acconeer/acconeer-python-exploration#33]
**Describe the bug**

I am getting a receive queue get timeout when I run the python exploration tool envelope service config for several hours.

**To reproduce**
Run my code for several hours on the Raspberry Pi 4 connected to the XB112 + XM112 via USB serial.

My code:
```
from threading import Thread
from time import sleep

class XB112(Thread):
    def __init__(self, device, callback):
        Thread.__init__(self)
        self._exit = False
        self._callback = callback

        self._client = UARTClient(device)

        self._client.squeeze = False

        config = configs.EnvelopeServiceConfig()
        config.sensor = [1] 
        config.range_interval = [0.04, 0.4]
        config.profile = config.Profile.PROFILE_2
        config.hw_accelerated_average_samples = 1
        config.downsampling_factor = 2
    
        self._info = self._client.setup_session(config)

    def stop(self):
        self._client.disconnect()
        self._exit = True

    def run(self):
        
        self._client.start_session()
    
        while not self._exit:
            info, data = self._client.get_next()    
            self._callback(data)

def callback_a(data):
    print(data)

def main():
    radar_sensor = XB112Collector(device="/dev/ttyUSB0", callback=callback_a)
    t1 = radar_sensor.start()
    while True:
        sleep(1)


if __name__ == "__main__":
    main()
```

**Traceback**

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/acconeer_exptool-3.2.8-py3.7.egg/acconeer/exptool/clients/links.py", line 304, in __get_into_buf
    data = self._recv_queue.get(timeout=self._timeout)
  File "/usr/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

**Environment (please complete the following information):**
 - Host OS: Raspbian
 - Acconeer hardware: Raspberry Pi 4 + XB112 + XM112
 - Acconeer software version: XM112 Module Software v2.0.0
 - Exploration version: v3.2.8

**Additional context**
Is there a way to decrease data rate in the envelope service config?  We don't need data at a high rate.  I am wondering that if the data rate is decrease and traffic on the USB serial decreases, this problem might go away.

**Comment by erikmansson** [comment]
Thanks for all valuable info!

Do you always get this error after the same amount of time? Or is it random?

You can set the update rate in the configuration:
```config.update_rate = 10```
And if necessary, get higher precision timing using:
```config.repetition_mode = config.RepetitionMode.SENSOR_DRIVEN```

However, this does not decrease the serial baud rate. That is possible, but requires modification to the client. The server and client starts at 115200 and then the client asks the server which maximum rate is supported, then switches to that. For the XM112, it's 3M.

This happens here:
https://github.com/acconeer/acconeer-python-exploration/blob/36eb9254c6a271526f588c0cf6cc4b1dd73ad4e3/src/acconeer/exptool/clients/reg/client.py#L203-L211

To set a lower rate, you could simply set for example:
```product_max_baudrate = 1000000```
in place of the register read.

Alternatively, you can set override_baudrate=115200 when creating the client. Then it won't switch at all. Though in most cases, that's too slow to be usable.
