### ISSUE TITLE
Can you provide a demo that can be used to detect heart rate? thanks

### ISSUE THREAD

**Issue by jiwenfei** [acconeer/acconeer-python-exploration#37]

**Comment by erikmansson** [comment]
We currently don't have any plans on making such a demo, but as a start you can use the lower right plot in the breathing module. Its (low pass) filter is adapted to movements from human pulse.  The filtering is done here:
https://github.com/acconeer/acconeer-python-exploration/blob/5231cdff07f9a3aa42c9d31a7c7123cbe8f2d287/examples/processing/breathing.py#L154

From there, you could experiment with adding a high pass filter, i.e., turning the filter into a band pass filter, to filter out unwanted movements.
