### ISSUE TITLE
Xm122 Bootloader

### ISSUE THREAD

**Issue by MuthukumarEC** [acconeer/acconeer-python-exploration#38]
I Lost boot loader file in XM122 module i can't  update code via in dfu where i get boot loader and softdevice of xm122 module.

**Comment by vackraetraed** [comment]
Hello MuthukumarEC,

The bootloader and flashdevice should be available as a hex file called "production_sw_xm122.hex"
In chapter 3.4 in https://developer.acconeer.com/download/xm122-sdk-user-guide-pdf/ you can find some about restoring the bootloader.

Best regards,
Anton
