### ISSUE TITLE
Hibernate mode can't be configured

### ISSUE THREAD

**Issue by sandroci** [acconeer/acconeer-python-exploration#46]
https://github.com/acconeer/acconeer-python-exploration/blob/71146f1c4346b0b40a0a73c0f94fc7ac8fbe3cd5/src/acconeer/exptool/configs.py#L59-L64

Unfortunately, the power save mode `hibernate` is missing here. In the [`regmap.yaml`](https://github.com/acconeer/acconeer-python-exploration/blob/5231cdff07f9a3aa42c9d31a7c7123cbe8f2d287/src/acconeer/exptool/data/regmap.yaml) `hibernate` is included but the `PowerSaveMode` class is lacking it. As workaround, I have included it by myself like following: 

```python 
class PowerSaveMode(ConfigEnum):
        ACTIVE = ("Active", "active")
        READY = ("Ready", "ready")
        SLEEP = ("Sleep", "sleep")
        OFF = ("Off", "off")
        HIBERNATE = ("Hibernate", "hibernate")
```

and reinstalled the python package. The `hibernate` mode is working with the `Sparse` service as expected. 

Can you fix that? 

Thank you in advance! 

Best regards,
Sandro

**Comment by erikmansson** [comment]
Thanks for your feedback! This has been left out because of limited hardware support - but I've now added it so you can use it. Note that it is only supported by the XM122.
