### ISSUE TITLE
Y-Axis misplaced 

### ISSUE THREAD

**Issue by RyFW** [acconeer/acconeer-python-exploration#47]
**Describe the bug**
As you can see in the screenshot, on all the graphs, the y-axis has slightly moved up. I have downloaded the exp.tool from GitHub again and tried, no change. Also have tried to re-install libraries etc. 

**Screenshots**
![image](https://user-images.githubusercontent.com/68332203/87542945-b3faa580-c69b-11ea-89c0-768792945012.png)

**Environment (please complete the following information):**
 - Host OS: Windows 10
 - Acconeer hardware: XM112
 - Acconeer software version: not changed since fresh board
 - Exploration version: v2.2.1.

**Additional context**

**Comment by erikmansson** [comment]
This is a known issue in PyQtGraph when using multiple monitors and DPI scaling in Windows. Unfortunately, they don't seem to have a fix for it yet.

https://github.com/pyqtgraph/pyqtgraph/issues/756
