### ISSUE TITLE
Unstability and down-time during measurements

### ISSUE THREAD

**Issue by patrickhz** [acconeer/acconeer-python-exploration#52]
Hello,

I am connected through the localhost port (127.0.0.1, without WIFI activated) as socket with my A111 on a Rpi 4 with the buster version of debian, and I have some issues regarding the measurements with either barebones.py as main or the GUI. Apparently I have some sort of down time where I cannot connect anymore, it is really confusing because it works from time to time with the same settings but I have no possibilities to troubeshoot the issue. Any feedback on that? 

**To reproduce**
for barebones:

in terminal:
python3 barebones.py -s localhost

or with GUI:
socket port: localhost

```
**Traceback**
Traceback (most recent call last):
  File "examples/record_data/barebones.py", line 61, in <module>
    main()
  File "examples/record_data/barebones.py", line 34, in main
    session_info = client.setup_session(config)
  File "/home/pi/Desktop/etacconeer/acconeer-python-exploration-master/src/acconeer/exptool/clients/base.py", line 64, in setup_session
    session_info = self._setup_session(config)
  File "/home/pi/Desktop/etacconeer/acconeer-python-exploration-master/src/acconeer/exptool/clients/json/client.py", line 87, in _setup_session
    info = self._init_session()
  File "/home/pi/Desktop/etacconeer/acconeer-python-exploration-master/src/acconeer/exptool/clients/json/client.py", line 151, in _init_session
    header, _ = self._recv_frame()
  File "/home/pi/Desktop/etacconeer/acconeer-python-exploration-master/src/acconeer/exptool/clients/json/client.py", line 175, in _recv_frame
    packed = self._link.recv_until(b'\n')
  File "/home/pi/Desktop/etacconeer/acconeer-python-exploration-master/src/acconeer/exptool/clients/links.py", line 101, in recv_until
    raise LinkError from e
acconeer.exptool.clients.links.LinkError
```

**Environment (please complete the following information):**
 - Host OS:  Rpi 4 and Debian, buster version
 - Acconeer hardware: A111
 - Acconeer software version: SDK? the one suggested for A111

**Comment by patrickhz** [comment]
sure,

`Server version v2.5.1
Waiting for new connections...
Got new connection.
Listening for command...
Got command:
{
	"cmd":	"get_version",
	"api_version":	3
}
Got command:
{
	"cmd":	"get_board_sensor_count",
	"api_version":	3
}
Got command:
{
	"cmd":	"iq_data",
	"sensors":	[1],
	"range_start":	0.18,
	"range_length":	0.60000000000000009,
	"repetition_mode":	"on_demand",
	"update_rate":	30,
	"gain":	0.5,
	"hw_accelerated_average_samples":	10,
	"profile":	2,
	"downsampling_factor":	1,
	"noise_level_normalization":	1,
	"maximize_signal_attenuation":	0,
	"sampling_mode":	0,
	"tx_disable":	0,
	"power_save_mode":	"active",
	"asynchronous_measurement":	1,
	"output_format":	"json+binary",
	"api_version":	3
}
00:09:59.134 [ 2388] (I) (rss) Radar system software activated
Starting iq service!
00:09:59.135 [ 2388] (I) (base_configuration) sensor 1 config: 10 1 11 2 7 1 ACTIVE A 0 0 0
00:10:01.142 [ 2388] (E) (sensor_protocol) Timeout waiting for event on sensor 1
00:10:01.142 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.142 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.142 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.142 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.142 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.142 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.142 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.142 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.142 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.142 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.142 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.142 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.142 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.142 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.142 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.143 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.143 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.143 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.143 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.143 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.143 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.143 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.143 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.143 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.143 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.143 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.143 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.143 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.143 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.143 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.143 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.143 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.144 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.144 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.144 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.144 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.144 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.144 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.144 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.144 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.144 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.144 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.144 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.144 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.144 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.144 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.144 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.144 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.144 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.144 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.145 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.145 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.145 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.145 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.145 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.145 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.145 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.145 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.145 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.145 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.145 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.145 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.145 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.145 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.145 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.145 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.146 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.146 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.146 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.146 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.146 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.146 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.146 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.146 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.146 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.146 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.146 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.146 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.146 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.146 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.146 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.146 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.146 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.147 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.147 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.147 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.147 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.147 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.147 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.147 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.147 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.147 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.147 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.147 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.147 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.147 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.147 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.147 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.147 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.147 [ 2388] (I) (sensor_diagnostics) Run_status running 431
00:10:01.148 [ 2388] (I) (sensor_diagnostics) WakeupInput[7..0]_wakeup_config: 0 24 0 0 0 0 0 0
00:10:01.148 [ 2388] (I) (sensor_diagnostics) Inputmux_wakeupinput[7..0]_config: 0 13 0 0 0 0 0 8
00:10:01.148 [ 2388] (I) (sensor_diagnostics) Timer[3..0]_wakeup_config: 0 0 0 0
00:10:01.149 [ 2388] (I) (sensor_diagnostics) asic_error_status: 0
00:10:01.149 [ 2388] (I) (sensor_diagnostics) Adc_too_fast: 0, Adc_fifo_full: 0, Spi_missing_ack: 0, Spi_unknown_cmd: 0, Stack_underflow: 0, Stack_overflow: 0
00:10:01.149 [ 2388] (I) (sensor_diagnostics) Stack_level_status_register: 0
00:10:01.149 [ 2388] (I) (sensor_diagnostics) Stack level 0: Addr=431
00:10:01.149 [ 2388] (I) (sensor_diagnostics) Stack level 1: Addr=430 Loop=0
00:10:01.149 [ 2388] (I) (sensor_diagnostics) Stack level 2: Addr=449 Loop=0
00:10:01.149 [ 2388] (I) (sensor_diagnostics) Stack level 3: Addr=0 Loop=0
00:10:01.149 [ 2388] (I) (sensor_diagnostics) Stack level 4: Addr=0 Loop=0
00:10:01.149 [ 2388] (I) (sensor_diagnostics) Stack level 5: Addr=0 Loop=0
00:10:01.149 [ 2388] (I) (sensor_diagnostics) Stack level 6: Addr=0 Loop=0
00:10:01.149 [ 2388] (I) (sensor_diagnostics) Stack level 7: Addr=0 Loop=0
00:10:01.149 [ 2388] (I) (sensor_diagnostics) asic_identity_number: 4370, interrupt_status: 80, Scratchpad Config 7: 3
00:10:01.149 [ 2388] (I) (sensor_diagnostics) Wakeup_status0_register: 1
00:10:01.150 [ 2388] (I) (sensor_diagnostics) vco_cbank_config: 4
00:10:01.150 [ 2388] (I) (sensor_diagnostics) pll_config: 122
00:10:01.150 [ 2388] (I) (sensor_diagnostics) Pll_div_config: 9
00:10:01.150 [ 2388] (E) (cpd_cbank_and_vana_calibration) Get CBank result failed
00:10:01.150 [ 2388] (E) (sensor_manager) Calibration failure for sensor 1
acc_service_create failed
00:10:01.150 [ 2388] (I) (rss) Radar system software deactivated
Waiting for new connections...
`

**Comment by erikmansson** [comment]
Ok so the actual issue is that you get a calibration failure here: `00:10:01.150 [ 2388] (E) (sensor_manager) Calibration failure for sensor 1`.

What hardware are you using? XC112 + XR112?

**Comment by vackraetraed** [comment]
Hello @patrickhz ,
Anton from Acconeer here.
How have you connected the Sparkfun board to the Raspberry? Simply by attaching it by its connector?
There is a known issue with the Sparkfun board where it outputs 5V from the interrupt pin and MISO pin to the Raspberry.
This might hurt the GPIOs on the Raspberry permanently.

Is it possible for you to run the example_assembly_test on the raspberry and report the log?

Best regards,
Anton

**Comment by patrickhz** [comment]
Hello, thanks again


```
pi@raspberrypi:~/Desktop/rpi_sparkfun/out $ ./example_assembly_test_rpi_sparkfun_a111_r2c 
Acconeer software version v2.5.1
00:04:07.819 [ 1007] (I) (rss) Radar system software activated
00:04:07.824 [ 1007] (I) (cpd_communication_test) ASIC identity test passed
00:04:07.844 [ 1007] (I) (cpd_communication_test) Register write-and-read test passed.
00:04:07.865 [ 1007] (I) (cpd_communication_test) Buffer write-and-read test passed
00:04:07.866 [ 1007] (W) (sensor_protocol) Spurious interrupt on sensor 1
00:04:07.866 [ 1007] (W) (sensor_protocol) Spurious interrupt on sensor 1
00:04:07.866 [ 1007] (W) (sensor_protocol) Spurious interrupt on sensor 1
00:04:07.866 [ 1007] (W) (sensor_protocol) Spurious interrupt on sensor 1
00:04:07.866 [ 1007] (W) (sensor_protocol) Spurious interrupt on sensor 1
00:04:07.866 [ 1007] (W) (sensor_protocol) Spurious interrupt on sensor 1
00:04:07.866 [ 1007] (W) (sensor_protocol) Spurious interrupt on sensor 1
00:04:07.866 [ 1007] (W) (sensor_protocol) Spurious interrupt on sensor 1
00:04:07.866 [ 1007] (W) (sensor_protocol) Spurious interrupt on sensor 1
00:04:07.866 [ 1007] (W) (sensor_protocol) Spurious interrupt on sensor 1
00:04:07.866 [ 1007] (W) (sensor_protocol) Spurious interrupt on sensor 1
00:04:07.866 [ 1007] (W) (sensor_protocol) Spurious interrupt on sensor 1
00:04:08.003 [ 1007] (W) (sensor_protocol) Spurious interrupt on sensor 1
00:04:08.003 [ 1007] (E) (sensor_protocol) Spurious interrupt tolerance 0 exceeded on sensor 1
00:04:08.003 [ 1007] (E) (cpd_interrupt_test) Failed to respond to consequent interrupts, the interrupt propagation delay from sensor to host may be too long
00:04:08.003 [ 1007] (E) (cpd_communication_test) Interrupt test failed
00:04:08.003 [ 1007] (I) (cpd_communication_test) Effective bit-rate: 12860 kbps
00:04:08.003 [ 1007] (I) (cpd_communication_test) SPI frame overhead: 36 us
Name: communication_read, result: Pass
Name: communication_write_read, result: Pass
Name: communication_interrupt, result: Fail
Name: supply, result: Fail
Name: clock, result: Fail
Assembly test: There are failed tests
00:04:08.003 [ 1007] (I) (rss) Radar system software deactivated
```

**Comment by adimarindra** [comment]
Hi, I got the same issue. I use Sparkfun A111 breakout on RPi 3B+ with Raspbian buster and got the same error messages when running examples.

**Comment by vackraetraed** [comment]
Hello,

I would probably try to control the interrupt pin manually. Try sending out a high value on the GPIO measure the voltage level and then use it as an input and try to read the value when a 3.3V voltage is applied.

Other than that, you could try to remove breakout board and attach it to the correct pins with cables instead. But instead of using the 5V pin use the 3.3V so that the Raspberry gets 3.3V logic back. (I would recommend this always when using Sparkfun with Raspberry)
