### ISSUE TITLE
update rate and fft of IQ Data

### ISSUE THREAD

**Issue by MDkontroller** [acconeer/acconeer-python-exploration#61]
HI guys!
would be happy if someone can help me with this.
I have save my meaurement of IQ data from raspberrypi C API in csv.
afterwards I have plot the amplitude of IQ along the depth aprox 1 m, till here great.
I wanted to get velocity from that, so I have arrange my data as  a columns (sweeps) and rows (data depth) this is aprox 
(100x 2066) complex elements, so 2066*0.5 mm => 1m.
however im stuck trying to get an fft of it and asociate it with the velocity in this case

here my code in python:

arr = pd.read_csv('motion.csv')
array = np.array(arr)
data_length = 2066
real = array[ :, 0]
img = array[ :, 1] 
cplex = real + 1j*img
NFFT = 16
ax =np.arange(0, data_length)
data_length = 2066
sweeps = int(len(cplex)/ data_length)
sw = cplex[0: 2066]

for i in range (sweeps-1):
    sw = np.vstack((sw, cplex[data_length*(i +1):data_length*(i+2)]))

ff = fft(sw,NFFT,axis =1)    //  as in obstacle_detection.py  
ff = ff / len(ff)
plt.ylabel('Amplitude')
plt.xlabel('Frequency')     // to correlate with the frequency bins.
plt.plot(np.arange(len(ff)),np.absolute(ff))
plt.show() 

![Figure_1](https://user-images.githubusercontent.com/43541921/101194464-553fc380-365e-11eb-933a-f6535ecf6452.png)

the fft has a shape of 116,16 
im not sure how to interpretate this data forward to get velocity, or how to gor forward with
I think im missing update_rate and NFFT, in the C API I coulnd find update_rate as its not avaliable for IQ service in C API.
could anyone give me an advice? 
thanks guys!

**Comment by erikmansson** [comment]
Hi,

I think the FFT might be applied in the wrong dimension, but it's difficult to follow your example without having the data available so we can run it ourselves. Could you share it?

You can set the update rate using `acc_base_configuration_repetition_mode_streaming_set(acc_base_configuration_t configuration, float update_rate)`. Please note that if it's set too high, it may not be realizable. In that case, `missed_data` in the `acc_service_iq_result_info_t` struct with be `true`.

Sorry for the late reply
