### ISSUE TITLE
XC112 board with kernel v5.4 ---- Device or resource busy

### ISSUE THREAD

**Issue by yilmaznaslan** [acconeer/acconeer-python-exploration#62]
Hi ,

I have followed the steps to install XC112 board with XR112 on raspberry pi however i am receving error;
**" could no write to gpio export: Dvice or resource busy".**

When I carefully read the readme file in doc I came up to this remark that the following line must be added for kernels v5.4 and newer.
- dtoverlay=spi0-cs,cs0_pin=8,cs1_pin=28

But in this documentation link in github  https://acconeer-python-exploration.readthedocs.io/en/latest/evk_setup/raspberry.html
this informations is available as follows;
- dtoverlay=spi0-1cs,cs0_pin=8

Which should we consider?
The kernel version on my Raspi is 5.4.79

Thank you

**Comment by erikmansson** [comment]
Both will work, but the first alternative may cause issues with ethernet, so we recommend the second:

```
dtoverlay=spi0-1cs,cs0_pin=8
```

The SDK docs will be updated in a future release.
