### ISSUE TITLE
Log files

### ISSUE THREAD

**Issue by ingleajinkya** [acconeer/acconeer-python-exploration#70]
Hello,

I was looking for log files, created by acconeer xc112 sensor while running main.py script.
I am using Rpi and raspberry pi OS. 
Can you help to locate the location of this log file.

**Comment by erikmansson** [comment]
The streaming server prints the log to stdout. If you want to log to file, redirect stdout by running the server like this:

    ./acc_streaming_server_... > /path/to/log_file.txt

**Comment by ingleajinkya** [comment]
Thank You
