### ISSUE TITLE
Can you provide the principle of breath rate detection in the python demo? 

### ISSUE THREAD

**Issue by jiwenfei** [acconeer/acconeer-python-exploration#72]
you have give the document of the  breath rate detection in sleeping, but not give the document of breath rate detection,Can you provide the principle of breath rate detection in the python demo?

**Comment by erikmansson** [comment]
Unfortunately, we currently don't have any documentation ready to share. Do you have any specific question about it?

**Comment by erikmansson** [comment]
Closing thus due to inactivity. Feel free to reopen!
