### ISSUE TITLE
Program the binary to XM132 via SWD connector

### ISSUE THREAD

**Issue by kangc0016** [acconeer/acconeer-python-exploration#74]
What hardware, connector and software can we use to program the binary for the XM132 using SWD 10-pin header on the development board?

**Comment by vackraetraed** [comment]
Hello kangc0016, thank you for the interest in our product.

At our office we usually use the following if we simply want to flash a binary on XM132 using SWD 10-pin header.

An Olimex adapter: https://www.digikey.se/product-detail/en/olimex-ltd/ARM-JTAG-20-10/1188-1016-ND/3471401
A JLink Base Compact: https://www.digikey.se/product-detail/en/segger-microcontroller-systems/8.19.00%2520J-LINK%2520BASE%2520COMPACT/899-1059-ND/7386652
And for firmware you can use STM32CubeProgrammer: https://www.st.com/en/development-tools/stm32cubeprog.html

As you can see the JLink is rather expensive, that is why we have given the option to flash a binary through USB using STM32CubeProgrammer.

Best regards,
Anton
