### ISSUE TITLE
XE132 USB device not showing

### ISSUE THREAD

**Issue by luisvillaran** [acconeer/acconeer-python-exploration#75]
I received a brand new XE132 board a few days ago from Digikey.  I tried following the start guides but can't get passed the first step of getting the board to show up as a USB device.  I get the following in the Device Manager:

![image](https://user-images.githubusercontent.com/4129872/113660263-8eae2d00-9658-11eb-8479-985c5682cb09.png)

I've tried multiple USB cables (I saw someone had an issue with that) and I tried installing the STM32 VCP drivers to no avail.  Any suggestions?

 - Host OS: Windows 10
 - Acconeer hardware:  XE132

**Comment by erikmansson** [comment]
Can you try [these](https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers) drivers?

**Comment by luisvillaran** [comment]
> Can you try [these](https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers) drivers?

The Universal Windows 10 driver on that page worked for me.  Thanks for your help!

**Comment by erikmansson** [comment]
Great!
