### ISSUE TITLE
XM132 can not be programmed

### ISSUE THREAD

**Issue by kangc0016** [acconeer/acconeer-python-exploration#79]
I bought a couple XM132, and trying to use STM32CubeProgrammer to program them, one failed, is there any way to diagnose this and figure out whether it is a hardware failure or software failure?

**Comment by vackraetraed** [comment]
Hello @kangc0016,

This is Anton from Acconeer.
Considering some devices are working, I assume you are flashing it correctly.
When does the failing device fail? Is it while flashing with STM32CubeProgrammer?
What error are you getting?

Best regards,
Anton

**Comment by erikmansson** [comment]
Closing this for now, feel free to reopen!
