### ISSUE TITLE
Is it possible for XR112 board to be connected directly in GPIO Pins of RPi?

### ISSUE THREAD

**Issue by Erwu117** [acconeer/acconeer-python-exploration#97]
Good day!
I have a question in regards to Acconeer's product “XR112” which is a pulsed radar breakout module, is it possible to connect it directly in one microcontroller (for example: RPi) without using the “XC112” evaluation board for the XR112? And how can I do it without using the evaluation board? I just find it expensive to buy both of the two products so I thought by this approach, I can make my project to be cost-effective.

**Comment by vackraetraed** [comment]
Hello @Erwu117 ,

You can not directly wire it, somehow you need to extract the signals from the flat cable then you would have to design level shifters for communication GPIOs and LDO/DCDC converter to supply the sensor with power.

Best regards,
Anton
